version: '2'

volume:
  presta-data:
  my-db:
services: 
  prestashop:
    image: prestashop
    ports:
      - 8002:80
    volumes:
      - presta-data:/var/www/html/
    links:
      - mysqldb
    depends_on:
      - mysqldb

  mysqldb:
    image: mysqldb
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: +QAY2wsx3edc
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestashopuser
      MYSQL_PASSWORD: +QAY2wsx3edc
    volumes:
      - my-db:/var/lib/mysql
  
  #tests:
  #   image: ps_test
  #   build:
  #    context: ./
  #    dockerfile: ./tests-fun/Dockerfile
  #   depends_on:
  #    - "prestashop"
  #   command: ["/tmp/wait-for-it.sh", "--timeout=1800", "--strict", "10.10.20.76:8001",  "--", "/usr/local/bin/python funtest.py"]
  #   tty: true
  #   volumes:
  #    - ./reports:/tests-fun/reports*/
     
     
