From mysql:5.7.31

command: mysqld --default-authentication-plugin=mysql_native_password
restart: always
ports:
   - 3308:3306
environment:
   MYSQL_ROOT_PASSWORD: +QAY2wsx3edc
   MYSQL_DATABASE: prestashop
   MYSQL_USER: prestashopuser
   MYSQL_PASSWORD: +QAY2wsx3edc
volumes:
   - ./dump.sql:/docker-entrypoint-initdb.d/datadump.sql
CMD tail -f /dev/null
