version: '2'

volume:
  D:/workEnvir/franck/prestadata: 
services: 
  prestashop:
    image: ps_build
    ports:
      - 8002:80
    volumes:
      - D:/workEnvir/franck/prestadata:/shared/
    links:
      - mysqldb
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7.31
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: +QAY2wsx3edc
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestashopuser
      MYSQL_PASSWORD: +QAY2wsx3edc
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
  
  tests:
     image: ps_test
     build:
      context: ./
      dockerfile: ./tests-fun/Dockerfile
     depends_on:
      - "prestashop"
     command: ["/tmp/wait-for-it.sh", "--timeout=1800", "--strict", "10.10.20.76:8001",  "--", "/usr/local/bin/python funtest.py"]
     tty: true
     volumes:
      - ./reports:/tests-fun/reports
     
     
