FROM mysql:5.7.31

ADD dump.sql /tmp/dump.sql

RUN /bin/bash -c "/usr/bin/mysqld_safe --skip-grant-tables &" && \
  sleep 5 && \
  mysql -u root -e "CREATE DATABASE prestashop" && \
  mysql -u root prestashop < tmp/dump.sql

