version: '2.1'

volumes:
  db-data:
 
services:
  mysql:
    image: mysql:5
    ports:
      - "3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: prestashop
      MYSQL_DATABASE: prestashop
    restart: always
    networks: 
      - prestashop2_default 
    
  prestashop-git:
    image: ps_build
    environment:
      DISABLE_MAKE: ${DISABLE_MAKE:-0}
      PS_INSTALL_AUTO: ${PS_INSTALL_AUTO:-1}
      DB_PASSWD: ${DB_PASSWD:-prestashop}
      DB_NAME: ${DB_NAME:-prestashop}
      DB_SERVER: ${DB_SERVER:-mysql}
      PS_DOMAIN: ${PS_DOMAIN:-prestashop-git}
      PS_FOLDER_INSTALL: ${PS_FOLDER_INSTALL:-install-dev}
      PS_FOLDER_ADMIN: ${PS_FOLDER_ADMIN:-admin-dev}
    command: ["/tmp/wait-for-it.sh", "--timeout=60", "--strict", "mysql:3306", "--", "/tmp/docker_run.sh"]
    ports:
      - "8001:80"
    networks: 
      - prestashop2_default   
  
  tests:
     image: ps_test
     build:
      context: ./
      dockerfile: ./tests-fun/Dockerfile
     depends_on:
      - "prestashop-git"
     command: ["/tmp/wait-for-it.sh", "prestashop-git:1200", "-s", "-t 1200",  "--", "/usr/local/bin/python funtest.py"]
     tty: true
     volumes:
      - ./reports:/tests/reports
     networks: 
        - prestashop2_default  
         
networks:
   prestashop2_default:
      driver: "bridge"
     
