version: '3'

services:
  
  prestashop:
    image: ps_build
    build:
      context: ../
      dockerfile: ../Dockerfile
    depends_on:
      - "db"
    networks:
      default:
        aliases:
          - prestashop-web

  db:
    image: mysql:5
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - default
  
  tests:
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      URL_FO: "http://10.10.20.71/"
      URL_BO: "http://10.10.20.71/admin/"
      EMAIL: "demo@prestashop.com"
      PASSWD: "prestashop_demo"
      HEADLESS: "true"
      DB_SERVER: "db"
    depends_on:
      - "prestashop"
      - "db"
    command: ["/tmp/wait-for-it.sh", "--timeout=1800", "--strict", "prestashop-web:80", "--", "/bin/bash"]
    command: ["python3 funtest.py"]
    tty: true
    volumes:
      - ./reports:/tests/reports
    networks:
      - default
